{{
    _ Extracts an archive file (tar.gz or zip)

    ARGS:
        file: Archive to extract
        extract-paths: Paths within the archive to extract
        dest-dir: Destination directory
}}tar --gzip --extract --no-same-owner --file {{ARGS["file"]}}{{if ARGS["dest-dir"]: --directory {{ARGS["dest-dir"]}}}}{{if ARGS["extract-paths"]: {{join(ARGS["extract-paths"], " ")}}}}
