ARG REPO=mcr.microsoft.com/dotnet/core/runtime
FROM $REPO:3.1-{{OS_VERSION}}{{ARCH_TAG_SUFFIX}}

# Install ASP.NET Core
RUN aspnetcore_version=3.1.5 \
    && wget -O aspnetcore.tar.gz https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/$aspnetcore_version/aspnetcore-runtime-$aspnetcore_version-linux-musl-{{ARCH_SHORT}}.tar.gz \
    && aspnetcore_sha512='{{if ARCH_SHORT = "arm64":3d97ffabe40743b86b5264c6eebe26af894a98dc71d35570a5288373be48b7fb5f65734a891ca48feeb2d0e10825c6aeb2d0d315d41049844c1a901c9a77b59b^else:b56aaefdd188106b47f3c20aa65f1fb3b9bdaca450e9599f132c178803119e7611ff8cde07c9248a49923dec1255d1e3e2fb53d7ec5807903c7bd1b1b9954a88}}' \
    && echo "$aspnetcore_sha512  aspnetcore.tar.gz" | sha512sum -c - \
    && tar -ozxf aspnetcore.tar.gz -C /usr/share/dotnet ./shared/Microsoft.AspNetCore.App \
    && rm aspnetcore.tar.gz
