parameters:
  name: null
  pool: {}
  matrix: {}
  dockerClientOS: null
  useRemoteDockerServer: false
jobs:
- job: ${{ parameters.name }}
  condition: and(succeeded(), ${{ parameters.matrix }})
  dependsOn: GenerateTestMatrix
  pool: ${{ parameters.pool }}
  strategy:
    matrix: $[ ${{ parameters.matrix }} ]
  steps:
  - template: ../steps/test-images.yml
    parameters:
      dockerClientOS:  ${{ parameters.dockerClientOS }}
      useRemoteDockerServer: ${{ parameters.useRemoteDockerServer }}
      setupImageBuilder: false
      setupTestRunner: true
